- src/main/java/com/futurenet/cotree/global/dto/response/ApiResponse.java
- src/main/java/com/futurenet/cotree/global/exception/ErrorCode.java
- src/main/java/com/futurenet/cotree/global/exception/RestApiException.java
- src/main/java/com/futurenet/cotree/global/exception/handler/GlobalExceptionHandler.java
- feat/global-response -> main
- ISSUE #1
> [FEAT/#1] 공통 처리 구조 설계

- src/main/java/com/futurenet/cotree/item/controller/CategoryController.java
- src/main/java/com/futurenet/cotree/item/controller/ItemController.java
- src/main/java/com/futurenet/cotree/item/dto/ItemDto.java
- src/main/java/com/futurenet/cotree/item/dto/response/CategoryListReponse.java
- src/main/java/com/futurenet/cotree/item/dto/response/ItemResponse.java
- src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
- src/main/java/com/futurenet/cotree/item/service/CategoryServiceImpl.java
- src/main/java/com/futurenet/cotree/item/service/ItemService.java
- src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
- src/main/resources/mapper/item/CategoryMapper.xml
- src/main/resources/mapper/item/ItemRepository.xml
[FEAT} 카테고리별 상품 조회
- feat/get-category-item ->  main
- ISSUE #15
- 카테고리 조회시 ID값으로 비교한 이유는 테이블 조인 줄이기 위해서 카테고리 이름이 아닌 ID값을 이용해서 했습니다.
> [FEAT} 카테고리별 상품 조회

- src/main/java/com/futurenet/cotree/tree/controller/TreeController.java
- src/main/java/com/futurenet/cotree/tree/dto/response/MyTreeResponse.java
- src/main/java/com/futurenet/cotree/tree/repository/TreeRepository.java
- src/main/java/com/futurenet/cotree/tree/service/TreeService.java
- src/main/java/com/futurenet/cotree/tree/service/TreeServiceImpl.java
- src/main/java/com/futurenet/cotree/tree/service/exception/InvalidExpValueException.java
- src/main/java/com/futurenet/cotree/tree/service/exception/TreeCreateFailedException.java
- src/main/java/com/futurenet/cotree/tree/service/exception/TreeErrorCode.java
- src/main/java/com/futurenet/cotree/tree/service/exception/TreeExpUpdateFailedException.java
- src/main/java/com/futurenet/cotree/tree/service/exception/TreeNotFoundException.java
- src/main/resources/mapper/tree/TreeMapper.xml
[FEAT] 내 나무 조회
- feat/tree -> main
- TreeController 생성 및 /tree 엔드포인트 추가
- TreeService의 getMyTree() 로직 _구현_
- TreeErrorCode 및 관련 예외 처리 추가
- Postman을 통해 로그인 후 /tree 호출 시 200 OK와 exp 값 응답 확인
- 존재하지 않는 유저로 호출 시 TREE_NOT_FOUND 예외 응답 확인
> [FEAT] 내 나무 조회

- src/main/java/com/futurenet/cotree/item/controller/ItemController.java
- src/main/java/com/futurenet/cotree/item/policy/PaginationPolicy.java
- src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
- src/main/java/com/futurenet/cotree/item/service/ItemService.java
- src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
- src/main/resources/mapper/item/ItemRepository.xml
[FEAT] 친환경 상품 조회
- feat/get-eco-item
- ISSUE #27
> [FEAT] 친환경 상품 조회

- src/main/java/com/futurenet/cotree/greenpoint/repository/GreenPointRepository.java
- src/main/java/com/futurenet/cotree/greenpoint/service/GreenPointService.java
- src/main/java/com/futurenet/cotree/greenpoint/service/GreenPointServiceImpl.java
- src/main/java/com/futurenet/cotree/greenpoint/service/exception/GreenPointErrorCode.java
- src/main/java/com/futurenet/cotree/greenpoint/service/exception/GreenPointInsertFailedException.java
- src/main/java/com/futurenet/cotree/greenpoint/service/exception/NotEnoughPointException.java
- src/main/java/com/futurenet/cotree/tree/constants/TreePolicy.java
- src/main/java/com/futurenet/cotree/tree/controller/TreeController.java
- src/main/java/com/futurenet/cotree/tree/dto/request/GiveWaterRequest.java
- src/main/java/com/futurenet/cotree/tree/dto/response/GiveWaterResponse.java
- src/main/java/com/futurenet/cotree/tree/repository/TreeRepository.java
- src/main/java/com/futurenet/cotree/tree/service/TreeService.java
- src/main/java/com/futurenet/cotree/tree/service/TreeServiceImpl.java
- src/main/java/com/futurenet/cotree/tree/service/exception/InvalidActionException.java
- src/main/java/com/futurenet/cotree/tree/service/exception/InvalidExpValueException.java
- src/main/java/com/futurenet/cotree/tree/service/exception/MaxExpReachedException.java
- src/main/java/com/futurenet/cotree/tree/service/exception/PointLackException.java
- src/main/java/com/futurenet/cotree/tree/service/exception/TreeErrorCode.java
- src/main/java/com/futurenet/cotree/tree/service/exception/TreeExpUpdateFailedException.java
- src/main/resources/mapper/greenpoint/GreenPointMapper.xml
- src/main/resources/mapper/tree/TreeMapper.xml
[FEAT] : 나무에 물주기
- feat/give-water - > main
- POST tree엔드포인트 추가
- 사용자 식별 기반의 물주기 요청 처리
- 물주기 성공 시 경험치 증가 처리
- 잔여 횟수 계산 및 반환
> [FEAT] : 나무에 물주기

- src/main/java/com/futurenet/cotree/tree/controller/TreeController.java
- src/main/java/com/futurenet/cotree/tree/domain/Tree.java
- src/main/java/com/futurenet/cotree/tree/dto/response/MyTreeResponse.java
- src/main/java/com/futurenet/cotree/tree/repository/TreeRepository.java
- src/main/java/com/futurenet/cotree/tree/service/TreeService.java
- src/main/java/com/futurenet/cotree/tree/service/TreeServiceImpl.java
- src/main/java/com/futurenet/cotree/tree/service/growth/GrowthCalculator.java
- src/main/java/com/futurenet/cotree/tree/service/growth/GrowthPlan.java
- src/main/java/com/futurenet/cotree/tree/service/growth/GrowthValidator.java
- src/main/resources/mapper/tree/TreeMapper.xml
[REFACTOR] : 물주기, 물 한꺼번에 주기 추상화
- refactor/get-tree -> main
- 물 한번 주기 /water
- 물 한꺼번에 주기 /water-all
> [REFACTOR] 물주기, 물 한꺼번에 주기 추상화

- src/main/java/com/futurenet/cotree/global/constant/PaginationConstants.java
- src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
- src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
- src/main/resources/mapper/item/ItemMapper.xml
[REFACTOR]페이지 네이션 글로벌 설정 및 메서드 이름 변경
- refactor/policy-method-change -> main
- ISSUE #39
> [REFACTOR]페이지 네이션 글로벌 설정 및 메서드 이름 변경

- src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
- src/main/java/com/futurenet/cotree/greenpoint/constant/GreenPointPolicy.java
- src/main/java/com/futurenet/cotree/member/controller/MemberController.java
- src/main/java/com/futurenet/cotree/member/dto/response/MyPageResponse.java
- src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
- src/main/java/com/futurenet/cotree/member/service/MemberFindService.java
- src/main/java/com/futurenet/cotree/member/service/MemberFindServiceImpl.java
- src/main/java/com/futurenet/cotree/member/service/exception/MemberErrorCode.java
- src/main/java/com/futurenet/cotree/order/constant/OrderStatus.java
- src/main/java/com/futurenet/cotree/order/dto/response/MemberOrderStatusResponse.java
- src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
- src/main/resources/mapper/member/MemberMapper.xml
- src/main/resources/mapper/order/OrderMapper.xml
- feat/mypage -> main
- ISSUE #45
> [FEAT] 마이페이지 조회 기능 구현

- build.gradle
- src/main/java/com/futurenet/cotree/global/config/AmazonS3Config.java
- src/main/java/com/futurenet/cotree/global/service/AmazonS3Service.java
- src/main/java/com/futurenet/cotree/member/controller/MemberController.java
- src/main/java/com/futurenet/cotree/member/dto/MemberUpdateAgeAndGenderDto.java
- src/main/java/com/futurenet/cotree/member/dto/MemberUpdateInfoDto.java
- src/main/java/com/futurenet/cotree/member/dto/request/MemberAgeAndGenderRequest.java
- src/main/java/com/futurenet/cotree/member/dto/request/MemberInfoUpdateRequest.java
- src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
- src/main/java/com/futurenet/cotree/member/service/MemberService.java
- src/main/java/com/futurenet/cotree/member/service/MemberServiceImpl.java
- src/main/java/com/futurenet/cotree/member/service/exception/MemberErrorCode.java
- src/main/resources/mapper/member/MemberMapper.xml
- feat/member-info-update -> main
- ISSUE #49
> [FEAT] 회원 정보 수정 기능

- src/main/java/com/futurenet/cotree/history/dto/request/MemberActionRequestEvent.java
- src/main/java/com/futurenet/cotree/history/handler/MemberActionEventHandler.java
- src/main/java/com/futurenet/cotree/history/repository/LogRepository.java
- src/main/java/com/futurenet/cotree/history/service/MemberActionLogService.java
- src/main/java/com/futurenet/cotree/history/service/MemberActionLogServiceImpl.java
- src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
- src/main/resources/mapper/history/LogRepository.xml
로그 폴더 이름 변경
- fix/folder-name-change -> main
-  ISSUE #57
> [FIX] 로그 폴더 이름 변경

- src/main/java/com/futurenet/cotree/shoppingbasket/controller/ShoppingBasketController.java
- src/main/java/com/futurenet/cotree/shoppingbasket/service/ShoppingBasketService.java
- src/main/java/com/futurenet/cotree/shoppingbasket/service/ShoppingBasketServiceImpl.java
[FIX] 장바구니 매개변수 변경
- hotfix/replace-itemId -> main
- 장바구니 매개변수 변경
> [FIX] 장바구니 매개변수 변경

- src/main/java/com/futurenet/cotree/member/controller/MemberController.java
- src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
- src/main/java/com/futurenet/cotree/member/service/MemberServiceImpl.java
- src/main/resources/mapper/member/MemberMapper.xml
- feat/member-age-gender -> main
- ISSUE #56
> [FIX]  나이 성별 입력 후 회원 상태 업데이트

- src/main/java/com/futurenet/cotree/auth/oauth2/handler/CustomOAuth2SuccessHandler.java
- src/main/java/com/futurenet/cotree/member/repository/MemberRepository.java
- src/main/resources/mapper/member/MemberMapper.xml
- feat/get-signup-status -> main
- ISSUE #61
> [FIX] 로그인 성공 후 리다이렉트 경로 설정

- src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
- src/main/resources/mapper/member/MemberMapper.xml
- fix/mypage -> main
- ISSUE #65
> [FIX] 마이페이지 조회 Null 처리

- src/main/java/com/futurenet/cotree/order/controller/OrderController.java
- src/main/java/com/futurenet/cotree/order/domain/Order.java
- src/main/java/com/futurenet/cotree/order/dto/OrderItemDto.java
- src/main/java/com/futurenet/cotree/order/dto/response/OrderItemResponse.java
- src/main/java/com/futurenet/cotree/order/dto/response/OrderResponse.java
- src/main/java/com/futurenet/cotree/order/repository/OrderItemRepository.java
- src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
- src/main/java/com/futurenet/cotree/order/service/OrderFacadeService.java
- src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
- src/main/java/com/futurenet/cotree/order/service/OrderItemService.java
- src/main/java/com/futurenet/cotree/order/service/OrderItemServiceImpl.java
- src/main/java/com/futurenet/cotree/order/service/OrderService.java
- src/main/java/com/futurenet/cotree/order/service/OrderServiceImpl.java
- src/main/resources/mapper/order/OrderItemMapper.xml
- src/main/resources/mapper/order/OrderMapper.xml
- feat/get-order -> main
- ISSUE #68
> [FEAT] 주문상태 조회

- src/main/java/com/futurenet/cotree/member/service/MemberFindServiceImpl.java
- src/main/java/com/futurenet/cotree/order/domain/Order.java
- src/main/java/com/futurenet/cotree/order/domain/OrderItem.java
- src/main/java/com/futurenet/cotree/order/dto/MemberOrderStatusDto.java
- src/main/java/com/futurenet/cotree/order/dto/request/OrderItemRegisterRequest.java
- src/main/java/com/futurenet/cotree/order/dto/response/OrderDetailResponse.java
- src/main/java/com/futurenet/cotree/order/repository/OrderItemRepository.java
- src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
- src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
- src/main/java/com/futurenet/cotree/order/service/OrderItemServiceImpl.java
- src/main/java/com/futurenet/cotree/payment/controller/PaymentController.java
- src/main/java/com/futurenet/cotree/payment/dto/request/PaymentConfirmRequest.java
- src/main/java/com/futurenet/cotree/payment/dto/request/PaymentRequest.java
- src/main/java/com/futurenet/cotree/payment/service/PaymentService.java
- src/main/java/com/futurenet/cotree/payment/service/PaymentServiceImpl.java
- src/main/resources/mapper/order/OrderItemMapper.xml
- src/main/resources/mapper/order/OrderMapper.xml
- feat/pay -> main
- ISSUE #78
> [FEAT] 결제 확정

- src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
- src/main/java/com/futurenet/cotree/order/repository/OrderItemRepository.java
- src/main/java/com/futurenet/cotree/tree/controller/TreeController.java
- src/main/java/com/futurenet/cotree/tree/dto/response/MyTreeSummaryResponse.java
- src/main/java/com/futurenet/cotree/tree/service/TreeService.java
- src/main/java/com/futurenet/cotree/tree/service/TreeServiceImpl.java
- src/main/java/com/futurenet/cotree/tree/service/exception/TreeErrorCode.java
- src/main/resources/mapper/order/OrderItemMapper.xml
[FEAT] 나무 정보 요약 조회
- feat/tree-summary -> main
- #79
> [FEAT] 나무 정보 요약 조회

- src/main/java/com/futurenet/cotree/item/controller/ItemController.java
- src/main/java/com/futurenet/cotree/item/repository/ItemRepository.java
- src/main/java/com/futurenet/cotree/item/service/ItemService.java
- src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
- src/main/resources/mapper/item/ItemMapper.xml
[FEAT]오늘의 상품 조회
- feat/today-item -> main
- ISSUE #81
> [FEAT]오늘의 상품 조회

- src/main/java/com/futurenet/cotree/order/domain/Order.java
- src/main/java/com/futurenet/cotree/order/dto/response/OrderResponse.java
- src/main/resources/mapper/order/OrderMapper.xml
- fix/order-status -> main
- ISSUE #88
> [FIX] 주문 조회 상태 반환

- src/main/java/com/futurenet/cotree/admin/controller/AdminEcoItemStatisticController.java
- src/main/java/com/futurenet/cotree/admin/dto/response/EcoPurchaseCategoryResponse.java
- src/main/java/com/futurenet/cotree/admin/dto/response/PopularEcoItemResponse.java
- src/main/java/com/futurenet/cotree/admin/repository/AdminEcoItemStatisticRepository.java
- src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticService.java
- src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticServiceImpl.java
- src/main/resources/mapper/admin/AdminEcoItemStatisticRepository.xml
- feat/admin-item-statistic -> main
-  ISSUE #101
> [FEAT] 상품 구매 데이터 통계

- src/main/resources/mapper/admin/AdminEcoItemStatisticRepository.xml
- fix/admin-statistic -> main
- ISSUE #104
> [FIX] 친환경 인기 상품 조회 쿼리 수정

- src/main/java/com/futurenet/cotree/admin/controller/AdminEcoItemStatisticController.java
- src/main/java/com/futurenet/cotree/admin/repository/AdminEcoItemStatisticRepository.java
- src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticService.java
- src/main/java/com/futurenet/cotree/admin/service/AdminEcoItemStatisticServiceImpl.java
- src/main/resources/application.yml
- src/main/resources/mapper/admin/AdminEcoItemStatisticRepository.xml
[FEAT] 관리자 통계
- feat/statistic-eco -> main
- ISSUE #102
> [FEAT] 관리자 통계

- src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
- src/main/java/com/futurenet/cotree/global/config/WebConfig.java
- fix/cors -> main
- ISSUE #107
> [FIX] cors 설정 변경

- src/main/java/com/futurenet/cotree/auth/oauth2/handler/CustomOAuth2SuccessHandler.java
[FIX] uri 변경
- fix/login-uri -> main
-  ISSUE #113
> [FIX] uri 변경

- src/main/java/com/futurenet/cotree/order/dto/request/OrderRequest.java
- fix/boolean-field -> main
- ISSUE #123
> [FIX] boolean 필드 JsonProperty 적용

- src/main/java/com/futurenet/cotree/order/controller/OrderController.java
- src/main/java/com/futurenet/cotree/order/repository/OrderRepository.java
- src/main/java/com/futurenet/cotree/order/service/OrderFacadeService.java
- src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
- src/main/java/com/futurenet/cotree/order/service/OrderService.java
- src/main/java/com/futurenet/cotree/order/service/OrderServiceImpl.java
- src/main/resources/mapper/order/OrderMapper.xml
- refactor/order-pagination -> main
- ISSUE #128
> [REFACTOR] 주문 조회 페이징 처리

- prometheus.yml
- src/main/java/com/futurenet/cotree/auth/security/config/SecurityConfig.java
- fix/monitoring-access -> main
- ISSUE #132
> [FIX] prometheus 접근 설정 변경

- build.gradle
- src/main/java/com/futurenet/cotree/global/config/CacheConfig.java
- src/main/java/com/futurenet/cotree/item/service/ItemServiceImpl.java
- feat/event-item-cache -> main
- ISSUE #136
> [FEAT] 행사 상품 조회 기능 캐시 적용

- src/main/java/com/futurenet/cotree/item/service/EventScheduler.java
- src/main/resources/mapper/item/EventItemMapper.xml
- fix/get-event-item-query -> main
- ISSUE #140
> [FIX] 행사 상품 조회 쿼리 수정

- src/main/java/com/futurenet/cotree/order/service/OrderFacadeServiceImpl.java
- refactor/order-deadlock -> main
- ISSUE #143
> [REFACTOR] 상품 정렬 후 수량 벌크 업데이트
